// <copyright file="CacheControlTest.TestParseCorrectlyParsesMaxAge.g.cs" company="Microsoft">Copyright © Microsoft 2010</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using MbUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace AshMind.Net.Tests.Of.Caching
{
    public partial class CacheControlTest {
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesMaxAge890()
{
    this.TestParseCorrectlyParsesMaxAge("max-ag\u0089=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesMaxAge421()
{
    this.TestParseCorrectlyParsesMaxAge("max-age=:5");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesMaxAge552()
{
    this.TestParseCorrectlyParsesMaxAge("");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesMaxAge1()
{
    this.TestParseCorrectlyParsesMaxAge(",ax-age=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesMaxAge841()
{
    this.TestParseCorrectlyParsesMaxAge
        ("s-maxage=15, private=\"field1, field2\", max-age=1:");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesMaxAge66()
{
    this.TestParseCorrectlyParsesMaxAge
        ("s-maxage=15\u0001 private=\"field1, field2\", max-age=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesMaxAge281()
{
    this.TestParseCorrectlyParsesMaxAge("Iax-age=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesMaxAge101()
{
    this.TestParseCorrectlyParsesMaxAge("max-age=)5");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesMaxAge55201()
{
    this.TestParseCorrectlyParsesMaxAge("");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesMaxAge102()
{
    this.TestParseCorrectlyParsesMaxAge(",ax-age=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesMaxAge932()
{
    this.TestParseCorrectlyParsesMaxAge("s-maxage=-:, max-age=-5");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesMaxAge36()
{
    this.TestParseCorrectlyParsesMaxAge("s-maxage=-:, max-age=-)");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesMaxAge422()
{
    this.TestParseCorrectlyParsesMaxAge
        ("s-maxage=15, private=\"field1, field2\", max-age=1)");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesMaxAge450()
{
    this.TestParseCorrectlyParsesMaxAge
        ("\u0100-maxage=15, private=\"field1, field2\", max-age=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesMaxAge770()
{
    this.TestParseCorrectlyParsesMaxAge("\t-\taxage=15, max-age=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesMaxAge762()
{
    this.TestParseCorrectlyParsesMaxAge(",,x-age=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesMaxAge279()
{
    this.TestParseCorrectlyParsesMaxAge("=");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesMaxAge409()
{
    this.TestParseCorrectlyParsesMaxAge
        ("s-maxage=15, private=\"\"i\"ld1, field2\", max-age");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesMaxAge89001()
{
    this.TestParseCorrectlyParsesMaxAge("max-ag\u0089=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesMaxAge42101()
{
    this.TestParseCorrectlyParsesMaxAge("max-age=:5");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesMaxAge55202()
{
    this.TestParseCorrectlyParsesMaxAge("");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesMaxAge103()
{
    this.TestParseCorrectlyParsesMaxAge(",ax-age=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesMaxAge210()
{
    this.TestParseCorrectlyParsesMaxAge
        ("\t-maxage=15, private=\"field1, field2\", max-age=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesMaxAge336()
{
    this.TestParseCorrectlyParsesMaxAge("s-maxage=:5, max-age=:5");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesMaxAge319()
{
    this.TestParseCorrectlyParsesMaxAge("s\tmaxage=15, max-age=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesMaxAge729()
{
    this.TestParseCorrectlyParsesMaxAge
        ("s-maxage=:5, private=\"field1, field2\", max-age=1:");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesMaxAge27901()
{
    this.TestParseCorrectlyParsesMaxAge("=");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesMaxAge956()
{
    this.TestParseCorrectlyParsesMaxAge("s-maxage=");
}
    }
}
