// <copyright file="CacheControlTest.TestParseCorrectlyParsesSharedMaxAge.g.cs" company="Microsoft">Copyright © Microsoft 2010</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using MbUnit.Framework;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Framework.Exceptions;

namespace AshMind.Net.Tests.Of.Caching
{
    public partial class CacheControlTest {
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge421()
{
    this.TestParseCorrectlyParsesSharedMaxAge("max-age=:5");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge497()
{
    this.TestParseCorrectlyParsesSharedMaxAge("\tax-age=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge552()
{
    this.TestParseCorrectlyParsesSharedMaxAge("");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge1()
{
    this.TestParseCorrectlyParsesSharedMaxAge(",ax-age=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge319()
{
    this.TestParseCorrectlyParsesSharedMaxAge("s\tmaxage=15, max-age=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge25()
{
    this.TestParseCorrectlyParsesSharedMaxAge("s-maxage=1\u00c9, max-age=:5");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void TestParseCorrectlyParsesSharedMaxAgeThrowsPexAssertFailedException629()
{
    this.TestParseCorrectlyParsesSharedMaxAge("s-maxage=15, max-age=1:");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void TestParseCorrectlyParsesSharedMaxAgeThrowsPexAssertFailedException137()
{
    this.TestParseCorrectlyParsesSharedMaxAge("s-maxage=15, max-age=)5");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void TestParseCorrectlyParsesSharedMaxAgeThrowsPexAssertFailedException577()
{
    this.TestParseCorrectlyParsesSharedMaxAge("s-maxage=15, max-age=-5");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void TestParseCorrectlyParsesSharedMaxAgeThrowsPexAssertFailedException527()
{
    this.TestParseCorrectlyParsesSharedMaxAge
        ("max-age\u008915, private\u0089\"field1, field2\", s-maxage=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void TestParseCorrectlyParsesSharedMaxAgeThrowsPexAssertFailedException429()
{
    this.TestParseCorrectlyParsesSharedMaxAge
        ("max-age\u010015, private=\"field1, field2\", s-maxage=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void TestParseCorrectlyParsesSharedMaxAgeThrowsPexAssertFailedException224()
{
    this.TestParseCorrectlyParsesSharedMaxAge
        ("max-age\u010015, pr\u0100vate=\"field1, field2\", s-maxage=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void TestParseCorrectlyParsesSharedMaxAgeThrowsPexAssertFailedException410()
{
    this.TestParseCorrectlyParsesSharedMaxAge("s-maxage=15, max-age");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge42101()
{
    this.TestParseCorrectlyParsesSharedMaxAge("max-age=:5");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge49701()
{
    this.TestParseCorrectlyParsesSharedMaxAge("\tax-age=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge55201()
{
    this.TestParseCorrectlyParsesSharedMaxAge("");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge101()
{
    this.TestParseCorrectlyParsesSharedMaxAge(",ax-age=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge891()
{
    this.TestParseCorrectlyParsesSharedMaxAge("\"\",-age=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge791()
{
    this.TestParseCorrectlyParsesSharedMaxAge("\"\"\t-age=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge95()
{
    this.TestParseCorrectlyParsesSharedMaxAge(",,\"-age=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge251()
{
    this.TestParseCorrectlyParsesSharedMaxAge("s-maxag\u0089=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge818()
{
    this.TestParseCorrectlyParsesSharedMaxAge("s-maxage=:5");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge55202()
{
    this.TestParseCorrectlyParsesSharedMaxAge("");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge804()
{
    this.TestParseCorrectlyParsesSharedMaxAge(",-maxage=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge465()
{
    this.TestParseCorrectlyParsesSharedMaxAge
        ("\u008bax-age=:5, private=\"field1, field2\", s-maxage=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge154()
{
    this.TestParseCorrectlyParsesSharedMaxAge
        ("max-age=:5, private=\"field1, field2\", s-maxage=:5");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge895()
{
    this.TestParseCorrectlyParsesSharedMaxAge
        ("m\tx-age=15, private=\"field1, field2\", s-maxage=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge496()
{
    this.TestParseCorrectlyParsesSharedMaxAge
        (",=x-age=15, private=\"field1, field2\", s-maxage=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge856()
{
    this.TestParseCorrectlyParsesSharedMaxAge
        ("max-age=15, private=\"field1, field2\", s-maxage=1)");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void TestParseCorrectlyParsesSharedMaxAgeThrowsPexAssertFailedException135()
{
    this.TestParseCorrectlyParsesSharedMaxAge("s-maxage=15, max-\"ge=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge405()
{
    this.TestParseCorrectlyParsesSharedMaxAge
        ("max-age=15, private=\"field1, field2\", s-maxage");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge25101()
{
    this.TestParseCorrectlyParsesSharedMaxAge("s-maxag\u0089=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge81801()
{
    this.TestParseCorrectlyParsesSharedMaxAge("s-maxage=:5");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge55203()
{
    this.TestParseCorrectlyParsesSharedMaxAge("");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge80401()
{
    this.TestParseCorrectlyParsesSharedMaxAge(",-maxage=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge189()
{
    this.TestParseCorrectlyParsesSharedMaxAge
        ("\u008bax-age=15, private=\"field1, field2\", s-maxage=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge794()
{
    this.TestParseCorrectlyParsesSharedMaxAge
        ("\u008bax-age=15, private=\"field1, field2\", s-maxage=1:");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void TestParseCorrectlyParsesSharedMaxAgeThrowsPexAssertFailedException772()
{
    this.TestParseCorrectlyParsesSharedMaxAge
        ("max-age=-5,\"private=\"field1, field2\", s-maxage=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void TestParseCorrectlyParsesSharedMaxAgeThrowsPexAssertFailedException718()
{
    this.TestParseCorrectlyParsesSharedMaxAge
        ("max-age=-5,\"pri\u0174ate=\"field1, field2\", s-maxage=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void TestParseCorrectlyParsesSharedMaxAgeThrowsPexAssertFailedException368()
{
    this.TestParseCorrectlyParsesSharedMaxAge
        ("max-age=-5,\"pri\u0174a\u0178e=\"field1, field2\", s-maxage=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge89501()
{
    this.TestParseCorrectlyParsesSharedMaxAge
        ("m\tx-age=15, private=\"field1, field2\", s-maxage=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void TestParseCorrectlyParsesSharedMaxAgeThrowsPexAssertFailedException842()
{
    this.TestParseCorrectlyParsesSharedMaxAge
        ("\"ax-age=15, private=\"field1, field2\", s-maxage=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge785()
{
    this.TestParseCorrectlyParsesSharedMaxAge
        ("max-age=:5, private=\"field1, field2\", s-maxage=)5");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void TestParseCorrectlyParsesSharedMaxAgeThrowsPexAssertFailedException293()
{
    this.TestParseCorrectlyParsesSharedMaxAge
        ("\t\tx-age=15,\"private=\"field1, field2\", s-maxage=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void TestParseCorrectlyParsesSharedMaxAgeThrowsPexAssertFailedException504()
{
    this.TestParseCorrectlyParsesSharedMaxAge
        ("=ax-age=15,\u0089private=\"field1, field2\", s-maxage=1=");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge9()
{
    this.TestParseCorrectlyParsesSharedMaxAge
        ("=ax-age=15,=private=\"field1, field2\", s-maxage=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void TestParseCorrectlyParsesSharedMaxAgeThrowsPexAssertFailedException439()
{
    this.TestParseCorrectlyParsesSharedMaxAge
        ("=ax-age=15,\u0089p,ivat\t=\"field1, field2\", s-maxage=\t5");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge25102()
{
    this.TestParseCorrectlyParsesSharedMaxAge("s-maxag\u0089=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge81802()
{
    this.TestParseCorrectlyParsesSharedMaxAge("s-maxage=:5");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge55204()
{
    this.TestParseCorrectlyParsesSharedMaxAge("");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge80402()
{
    this.TestParseCorrectlyParsesSharedMaxAge(",-maxage=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge537()
{
    this.TestParseCorrectlyParsesSharedMaxAge
        ("max-age=15, private=\"field1, field2\", s-maxage=1:");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge858()
{
    this.TestParseCorrectlyParsesSharedMaxAge
        ("max-age\u008915, private=\"field1, field2\", s-maxage=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge492()
{
    this.TestParseCorrectlyParsesSharedMaxAge
        ("max-age=15\u0001 private=\"field1, field2\", s-maxage=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge15401()
{
    this.TestParseCorrectlyParsesSharedMaxAge
        ("max-age=:5, private=\"field1, field2\", s-maxage=:5");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge279()
{
    this.TestParseCorrectlyParsesSharedMaxAge("=");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge840()
{
    this.TestParseCorrectlyParsesSharedMaxAge(",=maxage=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge40501()
{
    this.TestParseCorrectlyParsesSharedMaxAge
        ("max-age=15, private=\"field1, field2\", s-maxage");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge25103()
{
    this.TestParseCorrectlyParsesSharedMaxAge("s-maxag\u0089=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge81803()
{
    this.TestParseCorrectlyParsesSharedMaxAge("s-maxage=:5");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge55205()
{
    this.TestParseCorrectlyParsesSharedMaxAge("");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge80403()
{
    this.TestParseCorrectlyParsesSharedMaxAge(",-maxage=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge334()
{
    this.TestParseCorrectlyParsesSharedMaxAge("s-maxage=15\u0001 max-age=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge832()
{
    this.TestParseCorrectlyParsesSharedMaxAge("s-maxage\u008915, max-age\u008915");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge15402()
{
    this.TestParseCorrectlyParsesSharedMaxAge
        ("max-age=:5, private=\"field1, field2\", s-maxage=:5");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge141()
{
    this.TestParseCorrectlyParsesSharedMaxAge
        ("max-age=:5, private=\"field1, field2\", s-maxage=1:");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge397()
{
    this.TestParseCorrectlyParsesSharedMaxAge(",,maxage=15");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge27901()
{
    this.TestParseCorrectlyParsesSharedMaxAge("=");
}
[Test]
[PexGeneratedBy(typeof(CacheControlTest))]
public void TestParseCorrectlyParsesSharedMaxAge99()
{
    this.TestParseCorrectlyParsesSharedMaxAge("s-maxage=15, max-age");
}
    }
}
