// <copyright file="PexAssemblyInfo.cs" company="Microsoft">Copyright © Microsoft 2010</copyright>
// <auto-generated>
// This file should only contain assembly level attributes.
// Do not add any class or struct definitions as it may disable the ability of the tool to
// update the file.
// </auto-generated>

using System;

using Microsoft.Pex.Framework.Instrumentation;
using System.Globalization;

[assembly: PexInstrumentAssembly("AshMind.Extensions")]
[assembly: PexInstrumentType("mscorlib", "System.CultureAwareComparer")]
[assembly: PexInstrumentType(typeof(CompareInfo))]
